var __$1a49,__$1D0C=__$1D0C||null,__$1D3F=__$1D3F||null;
typeof __$1a49=="undefined"&&function(h,u,g){try{var p=function(){return"https:"==g.location.protocol?"https:":"http:"},i=38,m=u.userAgent.toLowerCase(),r=p()+"//analytics.strangeloopnetworks.com/",k=function(a,b,c){try{if(c&&g.URL.search(/(sljsdbg=true)(.*?)(&|$)/)!=-1)return r+"debug/"+(a=="slHead"?"slhead.js":"");var d=g.getElementById("slheadjs");d&&d.getAttribute(a)&&(b=d.getAttribute(a),b.indexOf("//")==0&&(b=p()+b));return b}catch(e){}},v=function(a,b){a.readyState?a.onreadystatechange=function(){/loaded|complete/.test(a.readyState)&&
b()}:(a.onload=function(){b()},a.onerror=function(){b()})},n=function(a,b){var c=g.createElement("script");c.type="text/javascript";c.async=!0;b&&v(c,b);c.src=a;var d=g.getElementsByTagName("script")[0];d.parentNode.insertBefore(c,d)},w=function b(a,d){if(a)if(a.length==0)d();else{var e=a.shift();e&&n(e,function(){b(a,d)})}},s=(new Function('return function(){var isIndirectEvalGlobal=function(original,Object){try{return(1,eval)("Object")===original}catch(err){return false}}(Object,123);if(isIndirectEvalGlobal)return function(expression){return(1,eval)(expression)};else if(typeof window.execScript!=="undefined")return function(expression,language){return window.execScript(expression,language)}}();'))(),
a={jsv:i,ua:m,tixUrl:k("tix",r,!1),tixAlt:k("alttix",null,!1),anaUrl:k("ana","/",!0),preUrl:k("pre","/",!0),slHead:k("slHead",null,!0),adp:k("adp","true",!1),ck:k("ck",null,!1),buf:k("buf","false",!1),wbv:(m.match(/.+(?:rv|it|ra|ie|me)[\/: ]([\d]+)/)||[])[1],msie:/msie/.test(m)&&!/opera/.test(m),firefox:/firefox/.test(m),chrome:/chrome/.test(m),safari:/webkit/.test(m)&&!/chrome/.test(m),webkit:/webkit/.test(m),log:function(b){a.consoleLogs=a.consoleLogs||[];a.consoleLogs.push(b);window.console&&console.log(b)},
startsWith:function(b,a){return b.substr(0,a.length)==a?!0:!1},append:function(b){try{var a=g.body||g.getElementById("slheadjs")||null;a&&a.appendChild(b)}catch(d){}},toQuery:function(b){function c(b,d,c){try{return b+d+"="+encodeURIComponent(c)}catch(e){a.e(e,"b","query",d+":"+c)}}var d="",e="?",f;try{for(f in b)b.hasOwnProperty(f)&&typeof b[f]!="function"&&(d+=c(e,f,b[f]),e="&")}catch(j){}return d},listen:function(b,c,d,e){try{b.addEventListener?b.addEventListener(c,d,e):b.attachEvent&&b.attachEvent("on"+
c,d)}catch(f){a.e(f,i,"slhead","r","listen")}},href:function(){try{if(typeof top!="undefined"&&top&&top.location&&top.location.href)return top.location.href}catch(b){}return""},err:{tLog:[],eat:function(b,c,d,e,f){try{if(this.enabled()){b=b||{name:"unknown",message:"",number:0};b.msg=encodeURIComponent(b.name+(b.message?": "+b.message:""));b.jsUrl=encodeURIComponent(g.URL||"unknown");b.jsFunction=d+"->"+this.tLog.join("->")+(e?"->"+e+"->":"")+(f?f:"");b.jsv=c;b.jsErrNum=b.jsErrNum||b.number||0;b.name=
b.message=b.number=function(){};a.log(b);if(!a.tixUrl)a.tixUrl=a.tixUrl?a.tixUrl:("https:"==g.location.protocol?"https:":"http:")+"//analytics.strangeloopnetworks.com/";var j=new Image;j.src=a.tixUrl+"sfinx.gif"+a.toQuery(b);a.append(j)}}catch(x){}},send:function(b,a,d){this.eat(b,a,d,null,null)},enabled:function(){return this.override?!0:k("err","false",!1)==="true"?!0:!1}},e:function(b,a,d,e){e=e!=null&&e.length>0?"("+encodeURIComponent(e)+")":"";this.err.tLog.unshift(a+":"+d+e);if(typeof b=="undefined")throw Error("undefined");
else throw b;},ee:function(b,a,d,e,f){this.e(b,a+"."+d,e,f)},exec:function(){try{if(a.stack&&a.stack.length>0){var b=a.stack.shift();if(b.length>0){var c=b.shift();a.cmd(c,b)}}}catch(d){a.err.eat(d,i,"slhead","r","exec")}},cmd:function(b,c){try{switch(b){case "slana":a.slana(c);break;case "slanasiteparams":a.slanasiteparams(c);break;case "preload":a.preload(c);break;case "deferrerload":a.deferrerload();break;case "pirload":a.pirload();break;case "supercacheload":a.supercacheload();break;default:a.err.eat({name:"unknown cmd",
message:b,number:43},i,"slhead","r","cmd","unknown command")}}catch(d){a.e(d,"r","cmd",null)}},head:new Date,paintTest:function(){try{a.paint=new Date,typeof top!="undefined"&&top&&top.window&&top.window.innerHeight&&top.window.innerWidth==0&&setTimeout(function(){a.paintTest()},16)}catch(b){}},slana:function(b){try{try{if(h.frameElement!=null){a.exec();return}}catch(c){a.exec()}this.body?a.exec():(this.body=this.paint=b.shift(),a.PagePackage=b,a.href().indexOf("slana=off")!=-1?a.exec():n(a.anaUrl+
"slana.js?Lo0P="+a.PagePackage[6],null))}catch(d){a.err.eat(d,i,"slhead","pg","slana")}},slanasiteparams:function(b){try{a.SitePackage=b,a.beacon.fire(),a.exec()}catch(c){a.err.eat(c,i,"slhead","pg","slanasiteparams")}},preload:function(b){try{try{if(h.frameElement!=null)return}catch(c){}a.preloadPkg=b;var d=a.evalPrefetch(b[7]);if(!(a.href().indexOf("slpbc=off")!=-1||!a.preloadPkg||a.preloader))if(b[1]!==""||b[2]!==""||b[3]!==""||b[4]!==""){var e=[];b[1]&&e.push(b[0]+"pdata.js?Lo0P="+b[1]);b[2]&&
e.push(b[0]+"cdata.js?Lo0P="+b[2]);b[3]&&e.push(b[0]+"gdata.js?Lo0P="+b[3]);b[4]&&e.push(b[0]+"mdata.js?Lo0P="+b[4]);w(e,function(){var c=a.preUrl+"slpre.js?Lo0P="+b[5];if(d)try{var e=g.createElement("iframe"),c=null;e.width=0;e.height=0;e.scrolling="no";e.style.border="0px";e.style.overflow="hidden";e.style.display="none";typeof g.domain!="undefined"&&g.domain&&g.domain.length>0&&(c="&d="+g.domain);var f=b[0]+"slpref.html?Lo0P="+b[6]+(c?c:"");g.getElementsByTagName("body")[0].appendChild(e);e.contentWindow.location.replace(f)}catch(o){a.err.eat(o,
i,"slhead","pg","prefetch")}else n(c,null)})}}catch(f){a.err.eat(f,i,"slhead","pg","preload")}},evalPrefetch:function(b){if(b==="mobile")return a.mobilePreload=!0,!1;if(a.adp==!0){if(b==="advanced")a.advanced=!0;return a.firefox}else if(!b||b==="auto")return a.firefox;else if(b==="advanced")return a.advanced=!0,a.firefox;else if(b==="true")return!0;return!1},pirload:function(){try{try{if(a.href().indexOf("slpir=off")!=-1){a.exec();return}}catch(b){}a.pir=__$1D0C.pir||{};try{a.pir.preloadImg=[];for(var c=
0,d=a.pir.list.length;c<d;++c)a.pir.preloadImg[c]=new Image,a.pir.preloadImg[c].src=a.pir.list[c];n(a.pir.src,function(){a.exec()})}catch(e){a.e(e,"pir","load",null)}}catch(f){a.err.eat(f,i,"slhead","pg","pirload")}},deferrerload:function(){try{try{if(a.href().indexOf("sldef=off")!=-1){a.exec();return}}catch(b){}a.deferrer.sortDeferrals();a.deferrer.process();a.exec()}catch(c){a.err.eat(c,i,"slhead","pg","deferrerload")}},supercacheload:function(){try{try{if(a.href().indexOf("slsc=off")!=-1){a.exec();
return}}catch(b){}a.mobile.init();a.mobile.addResourcesToLocalStorage();a.exec()}catch(c){a.err.eat(c,i,"slhead","pg","supercacheload")}},deferrer:{dwBuffer:[],modifiedPush:function(b){__$1D3F.deferred>0&&a.deferrer.process();__$1D3F.deferred[0]=b;a.deferrer.process()},swapEventLoading:function(b){try{if(h.addEventListener)__$SL_WAEL=h.addEventListener,h.addEventListener=function(a,c,f){a==="load"||a==="DOMContentLoaded"?__$1D3F.deferScript(b,c):__$SL_WAEL.apply(h,[a,c,f])},__$SL_DAEL=g.addEventListener,
g.addEventListener=function(a,c,f){a==="load"||a==="DOMContentLoaded"?__$1D3F.deferScript(b,c):__$SL_DAEL.apply(g,[a,c,f])};else if(h.attachEvent)__$SL_WAE=h.attachEvent,h.attachEvent=function(a,c){a==="onload"||a==="onreadystatechange"?__$1D3F.deferScript(b,c):__$SL_WAE(a,c)},__$SL_DAE=g.attachEvent,g.attachEvent=function(a,c){a==="onload"||a==="onreadystatechange"?__$1D3F.deferScript(b,c):__$SL_DAE(a,c)}}catch(c){a.err.eat(c,i,"slhead","deferrer","swapEventLoading")}},resetEventLoading:function(){try{if(h.addEventListener)h.addEventListener=
__$SL_WAEL,g.addEventListener=__$SL_DAEL;else if(h.attachEvent)h.attachEvent=__$SL_WAE,g.attachEvent=__$SL_DAE}catch(b){a.err.eat(b,i,"slhead","deferrer","resetEventLoading")}},process:function(){try{for(;__$1D3F.deferred.length>0;){var b=__$1D3F.deferred.shift(),c=typeof b[1],d=b[0];if(c=="string"){var e=b[1];a.deferrer.swapEventLoading(d);a.deferrer.captureDocumentWrite(d);a.deferrer.loadExternalJavaScript(d,e);return}else if(c=="function"){a.deferrer.swapEventLoading(d);a.deferrer.captureDocumentWrite(d);
try{b[1]()}catch(f){}a.deferrer.flushDocumentWriteBuffer(d,!1);a.deferrer.resetDocWrite();a.deferrer.resetEventLoading()}else if(c=="object")if(b[1].type=="i"||b[1].type=="iw"){var j=b[1].script,g=b[1].language||"JavaScript";if(b[1].type=="iw")var q=j.toString(),o=q.indexOf("{"),h=q.lastIndexOf("}"),j=q.substring(o+1,h);a.deferrer.swapEventLoading(d);a.deferrer.captureDocumentWrite(d);a.deferrer.loadInlineJavaScript(d,j,g);a.deferrer.flushDocumentWriteBuffer(d,!1);a.deferrer.resetDocWrite();a.deferrer.resetEventLoading()}else if(b[1].type==
"e"){e=b[1].filename;a.deferrer.swapEventLoading(d);a.deferrer.captureDocumentWrite(d);a.deferrer.loadExternalJavaScript(d,e);return}}if(__$1D3F.deferred.push!=a.deferrer.modifiedPush)__$1D3F.deferred.push=a.deferrer.modifiedPush}catch(l){a.err.eat(l,i,"slhead","deferrer","process")}},sortDeferrals:function(){try{__$1D3F.deferred=__$1D3F.deferred||[];for(var b=0;b<__$1D3F.deferred.length;b++)if(__$1D3F.deferred[b].length<3||!__$1D3F.deferred[b][2])__$1D3F.deferred[b][2]=1E6+b;__$1D3F.deferred.sort(function(a,
b){return a[2]-b[2]})}catch(c){a.e(c,"deferrer","sortDeferrals",null)}},captureDocumentWrite:function(b){try{if(b!="")a.deferrer.originalDw=g.write,a.deferrer.originalDwLn=g.writeln,a.deferrer.dwBuffer[b]="",g.write=function(c){a.deferrer.dwBuffer[b]+=c;a.deferrer.flushDocumentWriteBuffer(b,!0)},g.writeln=function(c){a.deferrer.dwBuffer[b]+=c+"\n";a.deferrer.flushDocumentWriteBuffer(b,!0)}}catch(c){a.e(c,"deferrer","deferrer",null)}},loadBufferedScriptTags:function(b,c,d){try{for(var c=[],e=[],f=
/<script(?:(?!src\s*?=)[\s\S])*?>([\s\S]*?)<\/script>/gi,j=/<script[^>]*?src\s*?=\s*?['"](.*?)['"][\s\S]*?>[\s\S]*?<\/script>/gi,g=/(type|language)=['"]?([\s\S]*?)['" >]/gi,i=/<script[\s\S]*?>[\s\S]*?<\/script>/gi,o=i.exec(d);o!=null&&o.length==1;){var h=j.exec(o[0]);if(h!=null&&h.length==2)c.push(h[0]),e.push([b,h[1]]);else{var l=f.exec(o[0]);if(l!=null&&l.length==2){c.push(l[0]);var m={type:"i"};m.script=l[1];var k=g.exec(l[0]);if(k!=null&&k.length==3&&k[2].toLowerCase().indexOf("vbscript")>-1)m.language=
"VBScript";e.push([b,m])}}o=i.exec(d)}if(e.length>0)__$1D3F.deferred=e.concat(__$1D3F.deferred);for(;c.length>0;)var n=c.shift(),d=d.replace(n,"")}catch(p){a.e(p,"deferrer","loadBufferedScriptTags",null)}return d},flushDocumentWriteBuffer:function(b,c){try{if(b!=""){var d=a.deferrer.dwBuffer[b],e=-1;if(c==!0){var f=["</iframe>","</div>"],j="",i=d.toLowerCase(),h;for(h in f)if(f.hasOwnProperty(h)){var o=i.lastIndexOf(f[h]);o>e&&(e=o,j=f[h])}if(e==-1)return;e+=j.length;var m=d.substr(0,e);a.deferrer.dwBuffer[b]=
d.slice(e);d=m}if(typeof d!="undefined"&&d!=""&&(c==!1||e!=-1)){var l=g.getElementById(b),d=a.deferrer.loadBufferedScriptTags(b,l,d),e=!1;if(a.msie){var i=d.toLowerCase(),f=["<style","<\!--"],k;for(k in f)if(f.hasOwnProperty(k)&&a.startsWith(i,f[k])){d="_"+d;e=!0;break}}l.innerHTML=d;e==!0&&l.removeChild(l.firstChild);for(var n=document.createDocumentFragment();l.firstChild;)n.appendChild(l.firstChild);l.parentNode.insertBefore(n,l)}}}catch(p){a.e(p,"deferrer","flushDocumentWriteBuffer",null)}},resetDocWrite:function(){g.write=
a.deferrer.originalDw;g.writeln=a.deferrer.originalDwLn},loadExternalJavaScript:function(b,c){try{n(c,function(){a.deferrer.flushDocumentWriteBuffer(b,!1);a.deferrer.resetDocWrite();a.deferrer.resetEventLoading();a.deferrer.process()})}catch(d){a.e(d,"deferrer","loadExternalJavaScript",null)}},loadInlineJavaScript:function(b,c,d){try{s?s(c,d):a.log("No technique for global eval available, script not executing.")}catch(e){a.e(e,"deferrer","loadInlineJavaScript",null)}}},sys:{jsv:18,cookie:{session:"SASId",
visitor:"SAVId",prefetch:"SAPref",latcheck:"SALat",getPrefetch:function(b){try{var c=b.sys.cookie.get(b.sys.cookie.prefetch),d=null;c!=null&&(d={list:c});d==null&&(d={list:"0"});d.save=function(b){try{b.sys.cookie.set(b.sys.cookie.prefetch,this.list,365,"/")}catch(c){a.e(c,"prefetch","save",null)}};return d}catch(e){b.e(e,"cookie","getPrefetch",null)}},getVisitor:function(){try{var b=this.get(this.visitor),c=null,d=null;b!=null&&(c=b.split(","),d=c.length>1?{vid:c[0]||a.sys.newUUID(),cvid:c[1]&&isNaN(c[1])&&
c[1]>0?c[1]:0}:a.sys.regx2Obj("(.*?)=(.*?);",b));d==null&&(d={vid:a.sys.newUUID(),nvid:1,cvid:0});d.save=function(){try{var b,c="";for(b in this)this.hasOwnProperty(b)&&typeof this[b]!="function"&&(c+=b+"="+this[b]+";");a.sys.cookie.set(a.sys.cookie.visitor,c,365,"/")}catch(d){a.e(d,"visitor","save",null)}};return d}catch(e){a.e(e,"cookie","getVisitor",null)}},getSession:function(){try{var b=this.get(this.session),c=null;b!=null&&(c=a.sys.regx2Obj("(.*?)=(.*?);",b));c==null&&(c={sid:a.sys.newUUID(),
csid:0,nsid:1});c.save=function(){try{var b="",c;for(c in this)this.hasOwnProperty(c)&&typeof this[c]!="function"&&(b+=c+"="+this[c]+";");a.sys.cookie.set(a.sys.cookie.session,b,null,"/")}catch(d){a.e(d,"session","save",null)}};return c}catch(d){a.e(d,"cookie","getVisitor",null)}},set:function(b,c,d,e){try{var f=b+"="+escape(c);if(d){var j=new Date;j.setTime(j.getTime()+d*864E5);f+="; expires="+j.toGMTString()}e&&(f+="; path="+escape(e));g.cookie=f}catch(i){a.e(i,"cookie","set",null)}},get:function(b){try{if(typeof b==
"undefined"||!b)return null;var b=" "+b+"=",c,d=null;try{d=" "+g.cookie+";"}catch(e){}return d&&(c=d.indexOf(b))>=0?(c+=b.length,d=d.substring(c,d.indexOf(";",c)),unescape(d)):null}catch(f){a.e(f,"cookie","get",null)}},erase:function(b,c){try{typeof b!="undefined"&&b&&this.set(b,"",-1,c)}catch(d){a.e(d,"cookie","erase",null)}}},newUUID:function(){try{for(var b=0,c=[],b=0;b<32;b++)c[b]="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".substr(Math.floor(Math.random()*62),1);return c.join("")}catch(d){a.e(d,
"sys","newUUID",null)}},regx2Obj:function(b,c){try{for(var d,e={},f=RegExp(b,"g"),j;(d=f.exec(c))!=null;){j=isNaN(d[2])?d[2]:parseInt(d[2],10);if(j=="true"||j=="false")j=j=="true"?!0:!1;e[d[1]]=j}return e}catch(g){a.e(g,"sys","regx2Obj",null)}},pre:{treat:function(b,c){try{if(typeof b=="undefined"||b==null)return null;if(typeof b.td=="undefined"||b.td==null||b.td==-1)return b.u?b.u:null;if(typeof c=="undefined"||c==null)return null;var d=h.location.host,e=!b.s||b.s==0?"http":"https";if((!b.h||b.h==
0)&&typeof c[b.td]!="undefined"&&c[b.td]!=null)d=c[b.td].d;return e+"://"+b.p+d+b.u}catch(f){a.ee(f,"sys","pre","treat",null)}},load:function(){try{a.preloader&&setTimeout(function(){a.log("Preloader starting...");if(a.sys)a.sys.pre.start=(new Date).getTime();a.preloader.stale()?a.preloader.reload():a.preloader.load()},16)}catch(b){a.ee(b,"sys","pre","load",null)}},start:(new Date).getTime(),fin:function(b,c){try{if(c.sys&&c.sys.cookie){var d=null,e=c.sys.cookie.getPrefetch(c);e.list==="0"?setTimeout(function(){c.sys.pre.fin(b,
c)},200):(d=c.sys.cookie.getVisitor(),d.pid=c.preloadPkg[1],d.pdx=d.plen,d.cid=c.preloadPkg[2],d.cdx=d.clen,d.gid=c.preloadPkg[3],d.gdx=d.glen,d.mid=c.preloadPkg[4],d.mdx=d.mlen,d.save(),e.save(c),c.sys.pre.close(b,c))}}catch(f){a.ee(f,"sys","pre","fin",null)}},close:function(b){try{b.close()}catch(c){a.ee(c,"sys","pre","close",null)}},count:function(b,c){try{if(c!=null)c[b]++,c.pt=(new Date).getTime()-a.sys.pre.start,c.save()}catch(d){a.ee(d,"sys","pre","count",null)}},cull:function(b){try{var c=
function(a,c,d,e,g,i){g[e]=0;if(typeof a!="undefined"&&a&&a.length>0)g[c]=b.preloadPkg[i],g[d]=0,g[e]=a.length},d=null;if(b.sys&&b.sys.cookie&&(d=b.sys.cookie.getVisitor(),d!=null))c(b.pList,"pid","pdx","plen",d,1),c(b.cList,"cid","cdx","clen",d,2),c(b.gList,"gid","gdx","glen",d,3),c(b.mList,"mid","mdx","mlen",d,4),d.pt=0,d.p=d.c=d.g=d.m=0,d.save();return d}catch(e){a.ee(e,"sys","pre","cull",null)}},prefetch:function(b,c){try{var d=function(d,e,f,i,h){for(;d.length>0;)if(i=d.shift(),g=c.sys.pre.treat(i,
e),g!=null&&(!window.location.href.match(/^https/i)||!g.match(/^http:/i)))typeof f!="undefined"&&(f[h]=!0),i.a&&a.chrome&&a.wbv>12?b.write('<link rel="prerender" href="'+g+'" />'):b.write('<link rel="prefetch" href="'+g+'" />')},e=null,f=null,g=null;if(c.sys&&c.sys.cookie)e=c.sys.cookie.getPrefetch(c),e.list="0",e.save(c),f=c.sys.pre.cull(c);if(c.sys)c.sys.pre.start=(new Date).getTime();f||(f=a.sys.cookie.getVisitor());c.pList&&c.pList.length>0&&d(c.pList,c.pTreatedDomains,f,"pdx","p");c.cList&&c.cList.length>
0&&d(c.cList,c.cTreatedDomains,f,"cdx","c");c.gList&&c.gList.length>0&&d(c.gList,c.gTreatedDomains,f,"gdx","g");c.mList&&c.mList.length>0&&d(c.mList,c.mTreatedDomains,f,"mdx","m");f.save();b.write('<link rel="prefetch" href="'+a.preloadPkg[0]+'slpref.gif" />');c.sys.pre.fin(b,c)}catch(i){a.ee(i,"sys","pre","prefetch",null)}}}},mobile:{initialized:!1,supportsLocalStorage:!1,LOCAL_STORAGE_PREFIX:"SL-",LOCAL_STORAGE_METADATA_PREFIX:"M-",LOCAL_STORAGE_CACHE_DAYS:7,init:function(){try{a.mobile.initialized=
!0,a.mobile.supportsLocalStorage="localStorage"in h&&h.localStorage!==null,a.log("Mobile SuperCache Init. Local Storage supported: "+a.mobile.supportsLocalStorage)}catch(b){a.err.eat(b,i,"slhead","mobile","init")}},addResourceToLocalStorageByTagName:function(b){try{for(var c=g.getElementsByTagName(b),d=c.length,b=0;b<d;b++){var e=c[b],f=e.innerHTML,j=e.attributes.slid;j&&f&&a.mobile.storeLocalResource(j.value,f)}}catch(h){a.err.eat(h,i,"slhead","mobile","addResourceToLocalStorageByTagName")}},addResourcesToLocalStorage:function(){try{!a.mobile.supportsLocalStorage==
!0?a.log("Local storage is not supported, not adding resources."):(a.mobile.measureLocalStorage(),a.mobile.purgeCache(),a.mobile.addResourceToLocalStorageByTagName("style"),a.mobile.addResourceToLocalStorageByTagName("script"))}catch(b){a.err.eat(b,i,"slhead","mobile","addResourcesToLocalStorage")}},existsInLocalStorage:function(b){try{return localStorage.getItem(a.mobile.LOCAL_STORAGE_PREFIX+a.mobile.LOCAL_STORAGE_METADATA_PREFIX+b)!=null?!0:!1}catch(c){a.err.eat(c,i,"slhead","mobile","existsInLocalStorage")}},
storeLocalResource:function(b,c){try{var d=a.mobile.LOCAL_STORAGE_PREFIX+b;a.log("Storing to Local Storage: "+d);localStorage.setItem(d,c);a.mobile.storeResourceMetadata(b)}catch(e){e==QUOTA_EXCEEDED_ERR?a.log("Local Storage is full."):a.err.eat(e,i,"slhead","mobile","storeLocalResource")}},storeResourceMetadata:function(b){try{var c=a.mobile.LOCAL_STORAGE_PREFIX+a.mobile.LOCAL_STORAGE_METADATA_PREFIX+b;a.log("Storing Metadata: "+c);var d=(new Date).getTime();localStorage.setItem(c,d)}catch(e){a.err.eat(e,
i,"slhead","mobile","storeResourceMetadata")}},measureLocalStorage:function(){try{for(var b=(new Date).getTime(),c=0,d=localStorage.length,e=0;e<d;e++){var f=localStorage.key(e),g=localStorage.getItem(f);c+=f.length;c+=g.length}var h=(new Date).getTime()-b;a.log("Currently "+c+" bytes in localStorage. ["+h+"ms]");return c}catch(k){a.err.eat(k,i,"slhead","mobile","measureLocalStorage")}},purgeCache:function(){try{var b=(new Date).getTime(),c=new Date;c.setDate(c.getDate()-a.mobile.LOCAL_STORAGE_CACHE_DAYS);
a.log("Purging resource older than: "+c.getTime());for(var d=a.mobile.LOCAL_STORAGE_PREFIX+a.mobile.LOCAL_STORAGE_METADATA_PREFIX,e=localStorage.length,f=[],g=0;g<e;g++){var h=localStorage.key(g);if(a.startsWith(h,d)&&localStorage.getItem(h)<=c.getTime()){var k=h.replace(d,"");f.push(k)}}e=f.length;for(g=0;g<e;g++){var k=f[g],m=a.mobile.LOCAL_STORAGE_PREFIX+k,h=d+k;localStorage.removeItem(m);localStorage.removeItem(h)}var n=(new Date).getTime()-b;a.log("Purged "+e+" resources from local storage. ["+
n+"ms]")}catch(l){a.err.eat(l,i,"slhead","mobile","purgeCache")}},clearLocalStorage:function(){try{for(var b=localStorage.length,c=0;c<b;c++){var d=localStorage.key(c);a.startsWith(d,a.mobile.LOCAL_STORAGE_PREFIX)&&localStorage.removeItem(d)}}catch(e){a.err.eat(e,i,"slhead","mobile","clearLocalStorage")}}}};h.__$1a49=a;a.paintTest()}catch(t){typeof console!="undefined"&&console.log(t),a.err.send(t,i,"slhead")}if(__$1D0C&&__$1D0C.stack&&__$1D0C.stack.length>0)a.load=__$1D0C.onload,a.stack=__$1D0C.stack,
a.exec()}(window,navigator,document);
